/*  Constraints for PRINT_JOB entity:
    There are four primary keys composing a composite key which are CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID and TRANSACTION_ID
*/
-- Defining primary keys
ALTER TABLE PRINT_JOB
ADD CONSTRAINT PK_PRINT_JOB PRIMARY KEY (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID); -- Defining primary keys for PRINT_JOB

-- Constraints: CUSTOMER_ID
-- ALTER TABLE PRINT_JOB
-- ADD CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE;

ALTER TABLE PRINT_JOB
MODIFY CUSTOMER_ID NOT NULL;

-- Constraints: KIOSK_ID
-- ALTER TABLE PRINT_JOB
-- ADD CONSTRAINT FK_KIOSK_ID FOREIGN KEY (KIOSK_ID) REFERENCES KIOSK(KIOSK_ID) ON DELETE CASCADE;

ALTER TABLE PRINT_JOB
MODIFY KIOSK_ID NOT NULL;

-- Constraints: DOCUMENT_ID
-- ALTER TABLE PRINT_JOB
-- ADD CONSTRAINT FK_DOCUMENT_ID FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT(DOCUMENT_ID) ON DELETE CASCADE;

ALTER TABLE PRINT_JOB
MODIFY DOCUMENT_ID NOT NULL;

-- Constraints: TRANSACTION_ID
-- ALTER TABLE PRINT_JOB
-- ADD CONSTRAINT FK_TRANSACTION_ID FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION_HISTORY(TRANSACTION_ID) ON DELETE CASCADE;

ALTER TABLE PRINT_JOB
MODIFY TRANSACTION_ID NOT NULL;

-- Constraints: JOB_DATE
ALTER TABLE PRINT_JOB
MODIFY JOB_DATE NOT NULL;

-- Constraints: JOB_TIME
ALTER TABLE PRINT_JOB
MODIFY JOB_TIME NOT NULL;

-- Constraints: JOB_STATUS
ALTER TABLE PRINT_JOB
ADD CONSTRAINT CHK_VALID_STATUS CHECK (JOB_STATUS IN ('Pending', 'Processing', 'Completed'));

ALTER TABLE PRINT_JOB
MODIFY JOB_STATUS DEFAULT 'Pending';

-- Constraints: NUMBER_OF_COPIES
ALTER TABLE PRINT_JOB
ADD CONSTRAINT CHK_POSITIVE_COPIES CHECK (NUMBER_OF_COPIES > 0);

ALTER TABLE PRINT_JOB
MODIFY NUMBER_OF_COPIES NOT NULL;

-- Constraints: TOTAL_PRICE
ALTER TABLE PRINT_JOB
ADD CONSTRAINT CHK_POSITIVE_PRICE CHECK (TOTAL_PRICE > 0);

ALTER TABLE PRINT_JOB
MODIFY TOTAL_PRICE NOT NULL;

-- Constraints: PAGES_PER_SHEET
ALTER TABLE PRINT_JOB
ADD CONSTRAINT CHK_POSITIVE_PAGES CHECK (PAGES_PER_SHEET > 0);

ALTER TABLE PRINT_JOB
MODIFY PAGES_PER_SHEET NOT NULL;

-- Constraints: ROTATION_OPTION
ALTER TABLE PRINT_JOB
MODIFY ROTATION_OPTION DEFAULT 0;

ALTER TABLE PRINT_JOB
ADD CONSTRAINT CHK_VALID_ROTATION CHECK (ROTATION_OPTION IN (0, 90, 180, 270));

-- Constraints: DOUBLE_SIDED_TYPE
ALTER TABLE PRINT_JOB
ADD CONSTRAINT CHK_DOUBLE_SIDED CHECK (DOUBLE_SIDED_TYPE IN ('None', 'Long edge', 'Short edge'));

ALTER TABLE PRINT_JOB
MODIFY DOUBLE_SIDED_TYPE DEFAULT 'None';

-- Constraints: PRINT_COLOR
ALTER TABLE PRINT_JOB
ADD CONSTRAINT CHK_PRINT_COLOR CHECK (PRINT_COLOR IN ('Black and White', 'Color'));

ALTER TABLE PRINT_JOB
MODIFY PRINT_COLOR DEFAULT 'Black and White';

-- Constraints: PAGE_RANGE
ALTER TABLE PRINT_JOB
MODIFY PAGE_RANGE NOT NULL;

ALTER TABLE PRINT_JOB
MODIFY PAGE_RANGE DEFAULT 'All';