-- Table creation for PRINT_JOB entity
CREATE TABLE PRINT_JOB (
    CUSTOMER_ID         NUMBER,
    KIOSK_ID            NUMBER,
    DOCUMENT_ID         NUMBER,
    TRANSACTION_ID      NUMBER,
    JOB_DATE            DATE,
    JOB_TIME            VARCHAR(50),
    JOB_STATUS          VARCHAR2(50),
    NUMBER_OF_COPIES    NUMBER,
    TOTAL_PRICE         NUMBER,
    PAGES_PER_SHEET     NUMBER,
    ROTATION_OPTION     NUMBER,
    DOUBLE_SIDED_TYPE   VARCHAR2(50),
    PRINT_COLOR         VARCHAR2(50),
    PAGE_RANGE          VARCHAR2(50)
);

-- Create table for CUSTOMER and KIOSK
CREATE TABLE CUSTOMER(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR2(255),
    CUSTOMER_USERNAME VARCHAR2(255),
    CUSTOMER_EMAIL VARCHAR2(255),
    CUSTOMER_PHONE_NO NUMBER,
    CUSTOMER_PASSWORD VARCHAR2(255),
    CUSTOMER_STATUS VARCHAR2(255),
    CUSTOMER_WORKPLACE VARCHAR2(255),
    CUSTOMER_DEPARTMENT VARCHAR2(255)
);

CREATE TABLE KIOSK(
    KIOSK_ID NUMBER,
    RECORD_ID NUMBER,
    KIOSK_ADDRESS VARCHAR2(255),
    KIOSK_STATUS VARCHAR2(255)
);

-- Create DOCUMENT table
CREATE TABLE DOCUMENT (
    DOCUMENT_ID NUMBER,
    DOCUMENT_NAME VARCHAR2(255),
    DOCUMENT_SIZE NUMBER,
    DATE_UPLOADED DATE
);

-- Create TRANSACTION_HISTORY table
CREATE TABLE TRANSACTION_HISTORY(
 TRANSACTION_ID NUMBER,
 TRANSACTION_METHOD VARCHAR2(255),
 TRANSACTION_AMOUNT NUMBER,
 TRANSACTION_STATUS VARCHAR2(255),
 TRANSACTION_DATE DATE,
 TRANSACTION_TIME VARCHAR2(255)
);

-- Table creation for ADMINISTRATOR entity
CREATE TABLE ADMINISTRATOR (
    ADMIN_ID NUMBER,
    ADMIN_NAME VARCHAR2(255),
    ADMIN_ADDRESS VARCHAR2(255),
    ADMIN_POSITION VARCHAR2(255),
    ADMIN_ACCESS_LEVEL VARCHAR2(255)
);

-- Table creation for REPORT_SYSTEM entity
CREATE TABLE REPORT_SYSTEM (
    RECORD_ID NUMBER,
    RECORD_DATE DATE,
    TOTAL_PRINT_JOBS NUMBER,
    TOTAL_SALES NUMBER,
    TOTAL_PAPER_USE NUMBER
);

-- Table creation for KIOSK_USAGE entity
CREATE TABLE KIOSK_USAGE (
    CUSTOMER_ID                 NUMBER,
    KIOSK_ID                    NUMBER,
    TRANSACTION_ID              NUMBER,
    ACCESS_DATE                 DATE,
    ACCESS_TIME                 VARCHAR(255),
    LOGOUT_TIME                 VARCHAR(255),
    KIOSK_USAGE_DURATION        VARCHAR(255)
);