-- Table creation for PRINT_JOB entity
CREATE TABLE PRINT_JOB (
    CUSTOMER_ID         NUMBER,
    KIOSK_ID            NUMBER,
    DOCUMENT_ID         NUMBER,
    TRANSACTION_ID      NUMBER,
    JOB_DATE            DATE,
    JOB_TIME            VARCHAR(50),
    JOB_STATUS          VARCHAR2(50),
    NUMBER_OF_COPIES    NUMBER,
    TOTAL_PRICE         NUMBER,
    PAGES_PER_SHEET     NUMBER,
    ROTATION_OPTION     NUMBER,
    DOUBLE_SIDED_TYPE   VARCHAR2(50),
    PRINT_COLOR         VARCHAR2(50),
    PAGE_RANGE          VARCHAR2(50)
);

-- Create table for CUSTOMER and KIOSK
CREATE TABLE CUSTOMER(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR2(30),
    CUSTOMER_USERNAME VARCHAR2(20),
    CUSTOMER_EMAIL VARCHAR2(30),
    CUSTOMER_PHONE_NO NUMBER,
    CUSTOMER_PASSWORD VARCHAR2(20),
    CUSTOMER_STATUS VARCHAR2(20),
    CUSTOMER_WORKPLACE VARCHAR2(30),
    CUSTOMER_DEPARTMENT VARCHAR2(20)
);
CREATE TABLE KIOSK(
    KIOSK_ID NUMBER,
    RECORD_ID NUMBER,
    KIOSK_ADDRESS VARCHAR2(50),
    KIOSK_STATUS VARCHAR2(20)
);

