-- AGNES
SELECT * FROM REPORT_SYSTEM RS 
  JOIN KIOSK Kiosk ON RS.RECORD_ID = Kiosk.RECORD_ID;

-- FIRZANAH
INSERT INTO TRANSACTION_HISTORY (TRANSACTION_ID, TRANSACTION_METHOD, TRANSACTION_AMOUNT, TRANSACTION_STATUS, TRANSACTION_DATE, TRANSACTION_TIME)
VALUES (333, 'online_banking', 50000.00, 'Pending', TO_DATE('2023-02-10', 'YYYY-MM-DD'), '14:00:00');

-- ISHWARI
-- test to check if constraints are working in admin_access_level
INSERT INTO ADMINISTRATOR(
    ADMIN_ID, ADMIN_NAME, ADMIN_ADDRESS, ADMIN_POSITION, ADMIN_ACCESS_LEVEL)
    VALUES ('624', 'Justin Lim', 'PETALING JAYA, SELANGOR', 'INTERN', 'BASIC LEVEL');
-- adding basic level which is not allowed 

-- POOI HUA
SELECT *
FROM PRINT_JOB PJ
JOIN KIOSK_USAGE KU ON PJ.CUSTOMER_ID = KU.CUSTOMER_ID
                    AND PJ.KIOSK_ID = KU.KIOSK_ID
                    AND PJ.TRANSACTION_ID = KU.TRANSACTION_ID;

-- KEVIN
