-- Data for PRINT_JOB entity
INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (1, 101, 201, 301, TO_DATE('2023-12-24', 'YYYY-MM-DD'), '12:30:00', 'Pending', 5, 20.50, 2, 90, 'Long edge', 'Color', '7-12');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (2, 102, 202, 302, TO_DATE('2023-12-24', 'YYYY-MM-DD'), '13:45:00', 'Processing', 3, 15.75, 1, 0, 'None', 'Black and White', 'All');
    
INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (3, 103, 203, 303, TO_DATE('2023-12-24', 'YYYY-MM-DD'), '14:20:00', 'Completed', 10, 40.00, 4, 180, 'Short edge', 'Color', '2-4');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (4, 104, 204, 304, TO_DATE('2023-12-24', 'YYYY-MM-DD'), '15:10:00', 'Pending', 2, 8.00, 1, 0, 'None', 'Black and White', 'All');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (5, 105, 205, 305, TO_DATE('2023-12-24', 'YYYY-MM-DD'), '16:05:00', 'Processing', 8, 32.00, 2, 90, 'Long edge', 'Color', '9-11');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (3, 106, 206, 306, TO_DATE('2023-12-24', 'YYYY-MM-DD'), '17:30:00', 'Completed', 4, 16.00, 1, 0, 'None', 'Black and White', 'All');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (7, 107, 207, 307, TO_DATE('2023-12-24', 'YYYY-MM-DD'), '18:45:00', 'Pending', 6, 24.50, 4, 180, 'Short edge', 'Color', '12-25');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (8, 108, 208, 308, TO_DATE('2023-12-24', 'YYYY-MM-DD'), '19:20:00', 'Processing', 1, 4.00, 1, 0, 'None', 'Black and White', 'All');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (9, 109, 209, 309, TO_DATE('2023-12-24', 'YYYY-MM-DD'), '20:15:00', 'Completed', 7, 28.00, 2, 90, 'Long edge', 'Color', '15-17');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (10, 110, 210, 310, TO_DATE('2023-12-24', 'YYYY-MM-DD'), '21:10:00', 'Pending', 3, 12.00, 1, 0, 'None', 'Black and White', 'All');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (11, 101, 211, 311, TO_DATE('2023-12-25', 'YYYY-MM-DD'), '10:30:00', 'Pending', 5, 20.50, 2, 90, 'Long edge', 'Color', '1-4');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (12, 102, 212, 312, TO_DATE('2023-12-25', 'YYYY-MM-DD'), '11:45:00', 'Processing', 3, 15.75, 1, 0, 'None', 'Black and White', 'All');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (3, 103, 213, 313, TO_DATE('2023-12-25', 'YYYY-MM-DD'), '12:20:00', 'Completed', 10, 40.00, 4, 180, 'Short edge', 'Color', '1-10');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (14, 101, 214, 314, TO_DATE('2023-12-25', 'YYYY-MM-DD'), '13:10:00', 'Pending', 2, 8.00, 1, 0, 'None', 'Black and White', 'All');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (15, 105, 215, 315, TO_DATE('2023-12-25', 'YYYY-MM-DD'), '14:05:00', 'Processing', 8, 32.00, 2, 90, 'Long edge', 'Color', '5-6');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (16, 106, 216, 316, TO_DATE('2023-12-25', 'YYYY-MM-DD'), '15:30:00', 'Completed', 4, 16.00, 1, 0, 'None', 'Black and White', 'All');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (17, 107, 217, 317, TO_DATE('2023-12-25', 'YYYY-MM-DD'), '16:45:00', 'Pending', 6, 24.50, 4, 180, 'Short edge', 'Color', '9-15');

INSERT INTO PRINT_JOB (CUSTOMER_ID, KIOSK_ID, DOCUMENT_ID, TRANSACTION_ID, JOB_DATE, JOB_TIME, JOB_STATUS, NUMBER_OF_COPIES, TOTAL_PRICE, PAGES_PER_SHEET, ROTATION_OPTION, DOUBLE_SIDED_TYPE, PRINT_COLOR, PAGE_RANGE)
VALUES (18, 108, 218, 318, TO_DATE('2023-12-25', 'YYYY-MM-DD'), '17:20:00', 'Processing', 1, 4.00, 1, 0, 'None', 'Black and White', 'All'); 