-- Select statements
SELECT * FROM PRINT_JOB;
SELECT * FROM PRINT_JOB WHERE CUSTOMER_ID = 3;
SELECT * FROM TRANSACTION_HISTORY;
SELECT * FROM TRANSACTION_HISTORY WHERE TRANSACTION_ID IN (313, 315, 316, 318);
SELECT * FROM KIOSK_USAGE;
SELECT * FROM KIOSK_USAGE WHERE TRANSACTION_ID = 343;

-- Finding primary keys that are foreign keys in other tables and are not referenced
SELECT *
FROM TRANSACTION_HISTORY
WHERE NOT EXISTS (
    SELECT *
    FROM KIOSK_USAGE
    WHERE KIOSK_USAGE.TRANSACTION_ID = TRANSACTION_HISTORY.TRANSACTION_ID
    );
SELECT *
FROM PRINT_JOB
WHERE NOT EXISTS (
    SELECT *
    FROM DOCUMENT
    WHERE DOCUMENT.DOCUMENT_ID = PRINT_JOB.DOCUMENT_ID
    );
SELECT * FROM DOCUMENT;
SELECT * FROM TRANSACTION_HISTORY;
SELECT *
FROM TRANSACTION_HISTORY TH
WHERE NOT EXISTS (
    SELECT 1
    FROM PRINT_JOB PJ
    WHERE PJ.TRANSACTION_ID = TH.TRANSACTION_ID
);

SELECT * FROM PRINT_JOB;

-- Screenshots for updated TRANS_HIS, KIOSK_USAGE, PRINT_JOB
SELECT * FROM TRANSACTION_HISTORY;
SELECT * FROM KIOSK_USAGE;
SELECT * FROM PRINT_JOB;

-- Display tables
SELECT * FROM PRINT_JOB;
SELECT * FROM CUSTOMER;
SELECT * FROM KIOSK;
SELECT * FROM DOCUMENT;
SELECT * FROM TRANSACTION_HISTORY;
SELECT * FROM ADMINISTRATOR;
SELECT * FROM REPORT_SYSTEM;
SELECT * FROM KIOSK_USAGE;

-- Delete tables
DROP TABLE PRINT_JOB;
DROP TABLE CUSTOMER;
DROP TABLE KIOSK;
DROP TABLE DOCUMENT;
DROP TABLE TRANSACTION_HISTORY;
DROP TABLE ADMINISTRATOR;
DROP TABLE REPORT_SYSTEM;
DROP TABLE KIOSK_USAGE;

-- Other delete statements
DELETE FROM PRINT_JOB;
DELETE FROM PRINT_JOB WHERE CUSTOMER_ID = 1;